[package]
name = "chess"
version = "0.0.0"
edition = "2021"

[dependencies]
winit = "0.27"
env_logger = "0.9"
log = "0.4"
pollster = "0.2"
cgmath = "0.18.0"
bytemuck = { version = "1.4", features = ["derive"] }
rand = "0.8.5"
image = { version =  "0.24", features = ["png"] }
erupt = "0.22.0+204"
thiserror = "1.0"
smallvec = "1.10"
